### PR TITLE
remove trailing spaces, convert tabs to spaces

### PR DESCRIPTION
**Pull request by keradus**
Remove trailing spaces, convert tabs to spaces, just to be better handled by git ;)

BTW, is this repo maintained?

### CODE REVIEW

**Comment by keradus** [comment]
ping @drewwilson

**Comment by keradus** [comment]
OK, repo is dead...

**Comment by danimesq** [comment]
Hi, @keradus 
I've forked TipTip to maintain it and use in all web projects of my community.
Please clone your pull request to: https://github.com/Software-js/TipTip
Thanks!

**Comment by keradus** [comment]
I stopped using it. If you want you could create PR on your own from my fork, the branch is still there.

**Pull request closed without merging**
